name:                glpk-headers
version:             0.3.0
github:              "prsteele/GlpkHs"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Low-level Haskell bindings to GLPK.
category:            Math

description:         Please see the README on GitHub at <https://github.com/prsteele/GlpkHs#readme>

dependencies:
  - base >= 4.7 && < 5
  - derive-storable >=0.1.2.0 && < 0.2

library:
  source-dirs: src

tests:
  GlpkHs-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    extra-libraries:
      - glpk
    dependencies:
      - glpk-headers
      - tasty
      - tasty-discover
      - tasty-hunit
